### ISSUE TITLE
Issues with Lack of Specification of Python Version and Version Incompatibilities Due to Missing requirements.txt File

### ISSUE THREAD

**Issue by emreerkangames** [mustafatosun/DAWN-Sim#1]
The Python version hasn't been specified. The requirements.txt file is missing. Due to the lack of explicitly stated dependencies, there are compatibility issues in the usage of the library.

**Comment by mustafatosun** [comment]
Thanks for your support. The requirements have been updated. You need to use Python version 3.10 or older. The names of some functions have changed after 3.11.
